# .github/workflows/test.yaml
name: Test Pipeline

on:
  workflow_call: # Required to accept triggers from other workflows
  
jobs:
  build:
      runs-on: ubuntu-latest
      steps:

        - uses: actions/checkout@v3
        - name: main pipeline
          run: |
              ls -la
