on:
  push:
    branches:
      - main
    paths:
      - '03_trigger/05_test'
      - '03_trigger/06_test'

jobs:
  # 1. First, check which paths changed
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - '03_trigger/05_test'

  # 2. Call the test workflow conditionally based on the path
  trigger-test-workflow:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.backend == 'true' }}
    uses: ./.github/workflows/test1.yaml # Points to the moved file
