
on:
 push:
   branches:
   - main
   paths:
   - '03_trigger/02_downstream'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: main pipeline
          run: |
            mkdir repo2
            echo test
            ls -la
            pwd
            cd repo2

        - name: Checkout a public repo
          uses: actions/checkout@v4
          with:
            repository: maxxam123/n8n-inbox

        - name: whats in
          run: |
            echo new
            pwd
            ls -la
            touch onetwo

        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.CROSS_2 }}
          with:
            source-directory: "repo2"
            destination-github-username: "maxxam123"
            destination-repository-name: "n8n-inbox"
            user-email: hennighausenmax@gmail.com
            target-branch: main

           
