
on:
 push:
   branches:
   - main
   paths:
   - '03_trigger/02_downstream'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: main pipeline
          run: |
            echo test
            ls -la

        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.CROSS }}
          with:
            source-directory: "n8n-inbox"
            destination-github-username: "maxxam123"
            destination-repository-name: "n8n-inbox"
            user-email: hennighausenmax@gmail.com
            target-branch: main
