
on:
 push:
   branches:
   - main
   paths:
   - '03_trigger/02_downstream'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:

        - uses: actions/checkout@v3
        - name: main pipeline
          run: |
            git clone https://github.com/maxxam123/n8n-in.git
            ls -la
            pwd
            cp -r wert/nummer1.txt n8n-in/
            ls -la n8n-in

                        
        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.CROSS_2 }}
          with:
            source-directory: "n8n-in"
            destination-github-username: "maxxam123"
            destination-repository-name: "n8n-in"
            user-email: hennighausenmax@gmail.com
            target-branch: main
           
